;;; cycbuf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cycbuf.el

(autoload 'cycbuf-switch-to-previous-buffer-no-timeout "cycbuf" "\
\\[cycbuf-switch-to-previous-buffer] switch to the previous buffer
in the buffer list.  Hide timeout is disabled" t)
(autoload 'cycbuf-switch-to-next-buffer-no-timeout "cycbuf" "\
\\[cycbuf-switch-to-previous-buffer] switch to the previous buffer
in the buffer list.  Hide timeout is disabled" t)
(autoload 'cycbuf-switch-to-previous-buffer "cycbuf" "\
\\[cycbuf-switch-to-previous-buffer] switch to the previous buffer
in the buffer list." t)
(autoload 'cycbuf-switch-to-next-buffer "cycbuf" "\
\\[cycbuf-switch-to-next-buffer] switch to the next buffer in the
buffer list." t)
(autoload 'cycbuf-mode "cycbuf" "\
Major mode for editing a subset of Emacs' buffers.
Aside from two header lines each line describes one buffer." t)
(autoload 'cycbuf-init "cycbuf" nil t)
(register-definition-prefixes "cycbuf" '("bsX-buffer-list" "cycbuf-"))

;;; End of scraped data

(provide 'cycbuf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cycbuf-autoloads.el ends here
